#!/usr/bin/env python3
"""Generate src/tui/themes-generated.ts from the official OpenCode TUI themes.

The JSONs come from the vendored reference tree
(tools/opencode-reference/tui/theme/assets/, pinned by
tools/sync-opencode.sh) so the theme arms re-sync with every reference pin.

Emits BOTH arms (dark + light) per theme — upstream theme JSONs carry
theme:{token:{dark,light}}. A token that upstream only defines for one arm
resolves to that value for both (arm cascade, never invented).

Usage: python3 tools/gen-themes.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "opencode-reference" / "tui" / "theme" / "assets"
VERSION_FILE = ROOT / "tools" / "opencode-reference" / "VERSION"
OUT = ROOT / "src" / "tui" / "themes-generated.ts"

# ThemeTokens mapping: token -> (theme key, fallback chain)
TOKEN_MAP = [
    ("bg", "background", ["backgroundPanel", "backgroundElement"]),
    ("panel", "backgroundPanel", ["backgroundElement", "background"]),
    ("surface", "backgroundElement", ["backgroundPanel", "background"]),
    ("border", "border", ["borderSubtle", "backgroundElement"]),
    ("borderActive", "borderActive", ["border", "borderSubtle"]),
    ("fg", "text", []),
    ("subtle", "textMuted", ["text"]),
    ("faint", "borderSubtle", ["border", "textMuted"]),
    ("brand", "text", []),
    ("accent", "primary", []),
    ("accentText", "background", []),
    ("user", "secondary", ["primary"]),
    ("assistant", "info", ["secondary"]),
    ("tool", "warning", []),
    ("warning", "warning", []),
    ("error", "error", []),
    ("success", "success", []),
    ("selected", "primary", []),
]

DIFF_MAP = [
    ("diffAdded", "diffAdded", ["success"]),
    ("diffRemoved", "diffRemoved", ["error"]),
    ("diffContext", "diffContext", ["subtle"]),
    ("diffAddedBg", "diffAddedBg", []),
    ("diffRemovedBg", "diffRemovedBg", []),
    ("diffContextBg", "diffContextBg", []),
    ("diffHunkHeader", "diffHunkHeader", []),
    ("diffHighlightAdded", "diffHighlightAdded", []),
    ("diffHighlightRemoved", "diffHighlightRemoved", []),
    ("diffLineNumber", "diffLineNumber", ["textMuted"]),
    ("diffAddedLineNumberBg", "diffAddedLineNumberBg", []),
    ("diffRemovedLineNumberBg", "diffRemovedLineNumberBg", []),
]

MD_MAP = [
    ("mdText", "markdownText", ["text"]),
    ("mdHeading", "markdownHeading", ["accent"]),
    ("mdLink", "markdownLink", ["primary"]),
    ("mdLinkText", "markdownLinkText", ["info"]),
    ("mdCode", "markdownCode", ["success"]),
    ("mdQuote", "markdownBlockQuote", ["warning"]),
    ("mdEmph", "markdownEmph", ["warning"]),
    ("mdStrong", "markdownStrong", ["warning"]),
    ("mdListItem", "markdownListItem", ["primary"]),
    ("mdListEnum", "markdownListEnumeration", ["info"]),
    ("synComment", "syntaxComment", ["textMuted"]),
    ("synKeyword", "syntaxKeyword", ["accent"]),
    ("synFunction", "syntaxFunction", ["primary"]),
    ("synVariable", "syntaxVariable", ["error"]),
    ("synString", "syntaxString", ["success"]),
    ("synNumber", "syntaxNumber", ["warning"]),
    ("synType", "syntaxType", ["warning"]),
    ("synOperator", "syntaxOperator", ["info"]),
    ("synPunct", "syntaxPunctuation", ["text"]),
]

ARMS = [("dark", ""), ("light", "_LIGHT")]


def resolve(value, defs, depth=0):
    if depth > 8:
        raise RuntimeError("def cycle")
    if isinstance(value, str) and value in defs:
        return resolve(defs[value], defs, depth + 1)
    return value


def pick(theme, key, fallbacks, defs, arm, crossed):
    def entry_raw(entry):
        if isinstance(entry, dict):
            v = entry.get(arm)
            if v is None:
                v = entry.get("dark" if arm == "light" else "light")
                if v is not None:
                    crossed.append(key)
            return v
        return entry

    raw = entry_raw(theme.get(key))
    if raw is not None:
        return resolve(raw, defs)
    for fb in fallbacks:
        raw = entry_raw(theme.get(fb))
        if raw is not None:
            return resolve(raw, defs)
    return None


def normalize(v):
    if v == "transparent":
        return "#00000000"
    if isinstance(v, str) and v.startswith("#") and len(v) == 4:
        return "#" + "".join(c * 2 for c in v[1:])
    return v


def is_hex(v):
    return isinstance(v, str) and v.startswith("#") and len(v) in (4, 5, 7, 9)


def main():
    names = sorted(p.stem for p in SRC.glob("*.json"))
    if not names:
        sys.exit(f"no theme json under {SRC}")
    version = VERSION_FILE.read_text().strip() if VERSION_FILE.exists() else "unknown pin"
    lines = [
        "// Generated by tools/gen-themes.py from the vendored opencode",
        f"// reference ({version}, tools/opencode-reference/) — DO NOT EDIT BY HAND.",
        "// GENERATED FILE — do not hand-edit.",
        "// Source: anomalyco/opencode (mirror of sst/opencode) dev branch,",
        "// packages/tui/src/theme/assets/*.json, fetched 2026-09-10.",
        "// Both arms per theme (theme:{token:{dark,light}}); a token upstream",
        "// defines for only one arm resolves to that value for both.",
        "// Regenerate: python3 tools/gen-themes.py",
        "",
        "export interface MdTokens {",
        *[f"  {name}: string;" for name, _, _fb in MD_MAP],
        "}",
        "",
    ]
    problems = []
    for arm, suffix in ARMS:
        crossed = []
        label = "dark arm" if arm == "dark" else "light arm (dark-cascaded where upstream omits light)"
        lines.append(f"// Exact OpenCode palettes ({label}), one entry per official theme.")
        lines.append(f"export const OFFICIAL_THEMES{suffix}: Record<string, {{")
        lines.extend(f"  {name}: string;" for name, _, _fb in TOKEN_MAP)
        lines.append("}> = {")
        md_lines = ["", "export const OFFICIAL_MD" + suffix + ": Record<string, MdTokens> = {"]
        diff_lines = ["", "export const OFFICIAL_DIFF" + suffix + ": Record<string, {", *[f"  {name}: string;" for name, _, _fb in DIFF_MAP], "}> = {"]
        for name in names:
            data = json.loads((SRC / f"{name}.json").read_text())
            defs = data.get("defs", {})
            theme = data.get("theme", {})
            tokens = {}
            for token, key, fallbacks in TOKEN_MAP:
                v = pick(theme, key, fallbacks, defs, arm, crossed)
                if v is None or not is_hex(v):
                    problems.append(f"{arm}/{name}: {token} ({key}) -> {v!r}")
                    v = "#000000"
                tokens[token] = normalize(v).lower()
            md = {}
            for token, key, fallbacks in MD_MAP:
                v = pick(theme, key, fallbacks, defs, arm, crossed)
                if v is None or not is_hex(v):
                    problems.append(f"{arm}/{name}: md.{token} ({key}) -> {v!r}")
                    v = "#000000"
                md[token] = normalize(v).lower()
            body = ", ".join(f"{k}: \"{v}\"" for k, v in tokens.items())
            lines.append(f"  \"{name}\": {{ {body} }},")
            mdbody = ", ".join(f"{k}: \"{v}\"" for k, v in md.items())
            md_lines.append(f"  \"{name}\": {{ {mdbody} }},")
            dv = {}
            for token, key, fallbacks in DIFF_MAP:
                v = pick(theme, key, fallbacks, defs, arm, crossed)
                if v is None:
                    v = {"diffAdded": "#4fd6be", "diffRemoved": "#c53b53", "diffContext": "#828bb8",
                         "diffAddedBg": "#20303b", "diffRemovedBg": "#37222c", "diffContextBg": "#1e1e1e",
                         "diffHunkHeader": "#828bb8", "diffHighlightAdded": "#b8db87", "diffHighlightRemoved": "#e26a75",
                         "diffLineNumber": "#8f8f8f", "diffAddedLineNumberBg": "#1b2b34", "diffRemovedLineNumberBg": "#2d1f26"}[token]
                dv[token] = normalize(v).lower()
            dbody = ", ".join(f"{k}: \"{v}\"" for k, v in dv.items())
            diff_lines.append(f"  \"{name}\": {{ {dbody} }},")
        lines.append("} as const;")
        lines.extend(md_lines)
        lines.append("} as const;")
        lines.extend(diff_lines)
        lines.append("} as const;")
        lines.append("")
        if crossed:
            from collections import Counter
            top = Counter(crossed).most_common(8)
            print(f"{arm}: {len(crossed)} token(s) arm-cascaded; by key: {top}")
    OUT.write_text("\n".join(lines).rstrip() + "\n")
    print(f"wrote {OUT} with {len(names)} themes × {len(ARMS)} arms")
    if problems:
        print("NON-HEX RESOLUTIONS (check these):")
        for p in problems:
            print(" ", p)


if __name__ == "__main__":
    main()
