#!/usr/bin/env python3
"""Generate src/tui/keybinds-generated.ts (the upstream keybind registry with
per-bind coverage classes) + docs/parity-keybinds.md (the machine-refreshed
gap list) from the vendored reference (tools/opencode-reference/).

Coverage classes come from tools/keybind-coverage.json: longest matching
prefix wins. They are an AUDIT, not wiring — nothing in the app reads them;
the value is that every upstream sync refreshes a measurable gap list, so
the next wave picks its target from data.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REF = ROOT / "tools" / "opencode-reference"
SRC_KEYBIND = REF / "tui" / "config" / "keybind.ts"
COVERAGE_CFG = ROOT / "tools" / "keybind-coverage.json"
OUT_TS = ROOT / "src" / "tui" / "keybinds-generated.ts"
OUT_MD = ROOT / "docs" / "parity-keybinds.md"

ENTRY_RE = re.compile(r'"?([\w.]+)"?:\s*keybind\(')
DESC_RE = re.compile(r'("((?:[^"\\]|\\.)*)")\s*$')


def parse_entries(text: str):
    """Scan the whole source (entries may span lines); for each `id: keybind(`
    capture the balanced-paren argument list, then split keys/description."""
    entries = []
    for m in ENTRY_RE.finditer(text):
        kid = m.group(1)
        start = m.end()  # after the open paren
        depth = 1
        i = start
        in_str = False
        while i < len(text) and depth > 0:
            ch = text[i]
            if in_str:
                if ch == '"':
                    in_str = False
            elif ch == '"':
                in_str = True
            elif ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            i += 1
        args = text[start : i - 1]
        dm = DESC_RE.search(args)
        if not dm:
            entries.append({"id": kid, "keys": "<unparsed>", "description": "", "raw": args.strip()[:60]})
            continue
        keys = parse_keys(args[: dm.start()])
        entries.append({"id": kid, "keys": keys, "description": dm.group(2)})
    return entries


def parse_keys(arg: str) -> str:
    arg = arg.strip()
    if arg.startswith('"'):
        return arg[1:].split('"')[0]
    m = re.search(r'key:\s*"([^"]+)"', arg)
    if m:
        return m.group(1)
    return "<complex>"


def load_coverage():
    cfg = json.loads(COVERAGE_CFG.read_text())
    prefixes = sorted(cfg["prefixes"].items(), key=lambda kv: -len(kv[0]))
    return prefixes, cfg.get("unmatched-default", "none")


def classify(kid: str, prefixes, default):
    for prefix, info in prefixes:
        if kid == prefix or kid.startswith(prefix):
            return info.get("status", "none"), info.get("note", "")
    return default, ""


def main():
    if not SRC_KEYBIND.exists():
        sys.exit("no vendored reference — run tools/sync-opencode.sh first")
    version = (REF / "VERSION").read_text().strip()
    text = SRC_KEYBIND.read_text()

    binds = []
    unmatched = []
    for entry in parse_entries(text):
        if entry["keys"] == "<unparsed>":
            unmatched.append(entry["raw"])
            continue
        binds.append(entry)

    prefixes, default = load_coverage()
    for b in binds:
        b["coverage"], b["note"] = classify(b["id"], prefixes, default)

    counts: dict[str, int] = {}
    for b in binds:
        counts[b["coverage"]] = counts.get(b["coverage"], 0) + 1

    ts = [
        "// Generated by tools/gen-keybinds.py from the vendored opencode",
        f"// reference ({version}, tools/opencode-reference/) — DO NOT EDIT BY HAND.",
        "// The registry is the parity AUDIT surface, not wiring: the app's own",
        "// keymap is hand-maintained; this file exists so every upstream sync",
        "// refreshes a measurable coverage report (see docs/parity-keybinds.md).",
        f"export const UPSTREAM_KEYBIND_VERSION = \"{version}\";",
        "",
        "export interface UpstreamKeybind {",
        "  id: string;",
        "  keys: string;",
        "  description: string;",
        '  coverage: "covered" | "partial" | "none" | "blocked-host" | "law";',
        "  note?: string;",
        "}",
        "",
        "export const UPSTREAM_KEYBINDS: UpstreamKeybind[] = [",
    ]
    for b in binds:
        note = f", note: \"{b['note']}\"" if b.get("note") else ""
        ts.append(
            f'  {{ id: "{b["id"]}", keys: "{b["keys"]}", description: "{b["description"]}", coverage: "{b["coverage"]}"{note} }},'
        )
    ts.append("];")
    ts.append("")
    ts.append(f"export const UPSTREAM_KEYBIND_COUNT = {len(binds)};")
    OUT_TS.write_text("\n".join(ts) + "\n")

    md = [
        "# Parity keybind coverage (GENERATED — do not edit by hand)",
        "",
        f"Upstream reference: **{version}** — {len(binds)} keybind definitions",
        "(packages/tui/src/config/keybind.ts). Classes from",
        "tools/keybind-coverage.json; regenerate with tools/gen-keybinds.py.",
        "",
        "| class | binds |",
        "|---|---|",
    ]
    for k in sorted(counts):
        md.append(f"| {k} | {counts[k]} |")
    md += ["", "Open surfaces (partial / none / blocked-host):", ""]
    for b in binds:
        if b["coverage"] in ("partial", "none", "blocked-host"):
            note = f" — {b['note']}" if b.get("note") else ""
            md.append(f"- `{b['id']}` ({b['keys']}) [{b['coverage']}]{note}")
    OUT_MD.write_text("\n".join(md) + "\n")

    print(f"wrote {OUT_TS.relative_to(ROOT)} and {OUT_MD.relative_to(ROOT)}")
    print(f"{version}: {len(binds)} binds — " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    if unmatched:
        print(f"UNPARSED {len(unmatched)} entries (kept out of the registry):")
        for line in unmatched[:5]:
            print("  " + line)


if __name__ == "__main__":
    main()
